name: Deploy Vite site to GitHub Pages

on:
  push:
    paths:
      - "website/**"   # deploy only when /website changes
      - ".github/workflows/pages.yml"
    branches: [ main ] # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional but recommended for Pages
      - uses: actions/configure-pages@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        working-directory: website
        run: npm ci

      - name: Build
        working-directory: website
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/dist   # vite output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

